#cloud-config
hostname: "tatooine"
coreos:
    etcd2:
      name: "tatooine"
      initial-cluster-token: starwars
      initial-advertise-peer-urls: http://$public_ipv4:2380
      listen-peer-urls: http://0.0.0.0:2380,http://0.0.0.0:7001
      listen-client-urls: http://0.0.0.0:4001
      advertise-client-urls: http://$public_ipv4:4001
      initial-cluster: tatooine=http://$public_ipv4:2380
      initial-cluster-state: new
    fleet:
      public-ip: $public_ipv4
      metadata: "hostname=naboo"
    flannel:
      interface: $public_ipv4
    units:
      - name: etcd2.service
        command: start
      - name: fleet.service
        command: start