#cloud-config
hostname: "fleet"
users:
    - name: "jarjar"
      passwd: "$1$o4wTm.HT$TyzV9aftAuUrQ9snvV5cA."
      groups:
        - "sudo"
        - "docker"
coreos:
    etcd2:
      name: "fleet"
      initial-cluster-token: starwars
      initial-advertise-peer-urls: http://$public_ipv4:2380
      listen-peer-urls: http://0.0.0.0:2380,http://0.0.0.0:7001
      listen-client-urls: http://0.0.0.0:4001
      advertise-client-urls: http://$public_ipv4:4001
      initial-cluster: fleet=http://$public_ipv4:2380
      initial-cluster-state: new
    fleet:
      public-ip: $public_ipv4
      metadata: "hostname=fleet"
    flannel:
      interface: $public_ipv4
    units:
      - name: etcd2.service
        command: start
      - name: fleet.service
        command: start